### PR TITLE
Add FRECNX token 

### PR DESCRIPTION
**Pull request by FreldoZL**
Website: https://ico.freldo.com/
Etherscan: https://etherscan.io/token/0xd8B8E1Eca89dA014E67fDbc2014eaA8E171079bF
Facebook: https://www.facebook.com/FreldoGroup/
Github: https://github.com/FreldoZL/FreldoCoinX
Linkedin: https://www.linkedin.com/company/freldo/
Reddit: https://www.reddit.com/user/FreldoICO
Telegram: https://t.me/FreldoChat
Twitter: https://twitter.com/FreldoGroup
Youtube: https://www.youtube.com/channel/UCWsvI0LW9v89ns4xEwYBD-w

Icon was added to cryptocurrency-icon
https://github.com/atomiclabs/cryptocurrency-icons/pull/351

### CODE REVIEW

**Comment by fsw** [comment]
Thanks @FreldoZL 
I had to simplify the icon to match others https://github.com/fsw/coffee.wallet/blob/develop/www/coins/frecnx.svg
(cryptocurrency-icon project does not accept ARs afaik as they make icons match each other)

This will be released in 0.11 release.

**Comment by FreldoZL** [comment]
I've seen that FRECNX token was committed to developer branch but it still doesn't appear in tokens list in your app. How soon it will be?

**Comment by fsw** [comment]
0.11 is in internal tests now and will be released in 2 weeks time

**Comment by FreldoZL** [comment]
Thank you

**Comment by fsw** [comment]
With small delay this is now awailable in 0.11

**Pull request merged**
